### ISSUE TITLE
Template design updates

### ISSUE THREAD

**Issue by maya** [18F/vote-gov#10]
Design tasks to implement into the templates:

**All**:
- [x] Add new design for the header @ericadeahl

**Homepage**:
- [x] Change the footer to be not fixed and make the vote icon cut into footer 
- [x] Get a gradient colors background from @carodew and implement (the blue background top is #225BA0 and bottom is #1C4B84)

**Internal page**:
- [x] Update the back button
- [x] Make inner pages more "full" in design @ericadeahl 
- [x] At mobile, reset margin top for h1 style and use 30px
- [x] Add padding to bottom of main content area

**Comment by ericadeahl** [comment]
Design updates:

Home (deactivated button)
![home](https://cloud.githubusercontent.com/assets/5911280/15370208/c3c238de-1cea-11e6-994b-50bf0a0d195f.png)

Home (state selected)
![home copy](https://cloud.githubusercontent.com/assets/5911280/15370211/c91cd82a-1cea-11e6-936d-91aca05322c5.png)

Register (text only)
![register](https://cloud.githubusercontent.com/assets/5911280/15370214/ce9af1ba-1cea-11e6-842c-a58c00dcf210.png)

Register (mail form)
![register by mail](https://cloud.githubusercontent.com/assets/5911280/15370217/d299d632-1cea-11e6-93b8-ff92ab804881.png)

**Comment by maya** [comment]
Looks great, thank you @ericadeahl!

**Comment by maya** [comment]
Finished in #34.
