### ISSUE TITLE
"g" cutoff in banner

### ISSUE THREAD

**Issue by maya** [18F/vote-gov#100]
<img width="628" alt="screen shot 2016-08-16 at 9 11 41 am" src="https://cloud.githubusercontent.com/assets/5249443/17706590/7ead4e94-6391-11e6-82ae-e6e7c4a9909a.png">

**Comment by jamesharnett** [comment]
It appears there are also other characters that are cutoff, including "ffi" and "i" from _official_, "b" and "i" from _website_, "f" from _of_, "h" from _the_, and "i" from _United_.

**Comment by maya** [comment]
cc: @rogeruiz
