### ISSUE TITLE
Add 404 page

### ISSUE THREAD

**Issue by yozlet** [18F/vote-gov#124]
We have no custom 404 page, so users see a default nginx 404, which is just awful.

What should a custom vote.gov 404 page look like? Whatever it is, I suggest we get something together quickly, then improve. There's also the possibility of routing all unrecognised URLs back to the front page, now that we have a custom `nginx.conf`.

**Comment by jamesharnett** [comment]
@yozlet Additionally, the default nginx 404 displays when a user doesn't select a state or territory (left as "") and clicks the "Find out how to register" button.

_Recommendation_: Disable the button until a user selects a valid state or territory (set gray background color), then enable and add transition in red background color to button.

**Comment by yozlet** [comment]
Good catch! I'd like to find a way to do this without JS if possible. (Alternatively, to ensure that the disabling only happens in JS.) In the meantime, I'm going to tweak the `nginx.conf` file to redirect those requests back to the front page.

**Comment by yozlet** [comment]
Fixed in #130. I'm going to add @jamesharnett's suggestion as a different issue.
