### ISSUE TITLE
voting accessibility

### ISSUE THREAD

**Issue by jpyuda** [18F/vote-gov#18]
What can voters expect? Where do they turn if unable to vote?

**Comment by kategarklavs** [comment]
@jpyuda Yes! Would you like me to post an update here about the status of this issue (copy info over from Trello)?

**Comment by jpyuda** [comment]
That would be great, thank you!

**Comment by kategarklavs** [comment]
@jpyuda Done!

So, here's the update on voting accessibility work:

Last week, I wrapped up two (very short) versions of the voting-accessibility-related copy I'd been working on for the past week or so. Here's the copy:

https://docs.google.com/a/gsa.gov/document/d/1EIkWWjH-bDzVtlVnsmRBE3EZ6oimBobJbECLuoMt6wQ/edit?usp=sharing

The team has already shared feedback, which I've incorporated. At this stage, I think the copy is ready to be picked up by a designer — any takers? 😎

**Comment by kategarklavs** [comment]
And, one more note: I'm happy to use either version of the text. The first is a bit more to the point, though the second has the bonus of reinforcing the legal requirements underpinning voting-accessibility measures. @jpyuda and @megdaly, do you have a strong preference for one version over the other? (Alternatively, if you'd like me to come up with another version, I'd be happy to do that, too.)

**Comment by megdaly** [comment]
@kategarklavs Hi Kate! I like the second option better, since it mentions the laws and the HAVA mandate.

**Comment by kategarklavs** [comment]
@megdaly Excellent! Let's go with the second option, then.

cc @jpyuda
