### ISSUE TITLE
Fix linting errors and warnings

### ISSUE THREAD

**Issue by rogeruiz** [18F/vote-gov#51]
There are a small number of linting errors and warnings for codebase. Deployment
is currently failing on CircleCI because of this. Let's fix the linter warnings
and error before the codebase grows any more. 💯

### Errors & Warnings
- [ ] **vote-gov/assets/styles/main.scss**
    - [ ] main.scss:96 [W] TrailingWhitespace: Line contains trailing whitespace
    - [ ] main.scss:114 [W] SelectorDepth: Selector should have depth of applicability no greater than 2, but was 3
    - [ ] main.scss:135 [W] ColorVariable: Color literals like `#003366` should only be used in variable declarations; they should be referred to via variable everywhere else.
    - [ ] main.scss:144 [W] TrailingWhitespace: Line contains trailing whitespace
    - [ ] main.scss:146 [W] SelectorDepth: Selector should have depth of applicability no greater than 2, but was 3
    - [ ] main.scss:164 [W] TrailingWhitespace: Line contains trailing whitespace
    - [ ] main.scss:266 [W] TrailingWhitespace: Line contains trailing whitespace
- [ ] **vote-gov/assets/scripts/start.js**
    - [ ] 3:1   warning  Unexpected console statement  no-console
    - [ ] 3:52  error    Missing semicolon             semi
    - [ ] 4:1   warning  Unexpected console statement  no-console

![screen shot 2016-05-23 at 4 59 26 pm](https://cloud.githubusercontent.com/assets/706004/15484405/de4eacd4-2107-11e6-9e4b-2f0b57345976.png)

**Comment by maya** [comment]
@rogeruiz I don't agree with this rule:
```
 main.scss:135 [W] ColorVariable: Color literals like #003366 should only be used in variable declarations; they should be referred to via variable everywhere else.
```

A new variable should be created only when **all** of the following criteria are met:

- the value is repeated at least twice;
- the value is likely to be updated at least once;
- all occurrences of the value are tied to the variable (i.e. not by coincidence).

http://sass-guidelin.es/#variables

**Comment by maya** [comment]
Nm bringing the above to the front end guild to discuss first.

**Comment by rogeruiz** [comment]
Sound good @maya. I'll leave this closed and we can reopen it as new errors creep up.
