### ISSUE TITLE
Automated build step for multi-lingual sites

### ISSUE THREAD

**Issue by rogeruiz** [18F/vote-gov#58]
Currently, the deployment strategy only focuses on a single build step. There should be a repeatable automated process for building multiple Hugo sites and then synchronizing all the changes within a single public directory.

### Acceptance Criteria

- [x] Leverage the `npm run *` scripts in the `package.json`
- [x] Ensure that all multi-lingual sites are deployed to ☁️.gov

**Comment by rogeruiz** [comment]
@yozlet 💡 
https://github.com/18F/vote-gov/pull/70#discussion_r65763859

**Comment by rogeruiz** [comment]
Once #78 lands on `staging`, this can be closed.

**Comment by yozlet** [comment]
#78 Merged!
