### ISSUE TITLE
State selections won't work without JavaScript

### ISSUE THREAD

**Issue by rogeruiz** [18F/vote-gov#66]
Currently, the state selection process is done either with a drop down menu or a Typeahead input area. Both of these require JavaScript on the page. Should there be a way to display all states if there is no JavaScript detected on the page? Perhaps a scrollable list of some kind?

cc: @jpyuda @bradnunnally @ericadeahl

**Comment by rogeruiz** [comment]
The code necessary to make the select drop down menu work for page navigation.

https://github.com/18F/vote-gov/blob/staging/layouts/index.html#L47-L58

**Comment by jpyuda** [comment]
Let's get something shipped that works with javascript to start, then we can circle back and design the fallback.

**Comment by rogeruiz** [comment]
I will close this for now, and we can reopen it when we circle back. Thanks @jpyuda
