### ISSUE TITLE
Seriously Include Texas As A State

### ISSUE THREAD

**Issue by djeraseit** [18F/vote-gov#76]
Here is a link to the application:
http://www.votetexas.gov/register-to-vote/

Irrespective of President's Obama's recent speech and visit to Austin, TX, there needs to a least be a link and/or instructions with application.

**Comment by rogeruiz** [comment]
Thanks for raising this issue @djeraseit. We've been moving quickly on updating the content on the site with #70 and captured the missing states in that PR.

Here's the relevant commit, https://github.com/18F/vote-gov/pull/70/commits/e0551e137d7ebd2341952a19dbdf13bb255f02ce

Once #70 lands in `staging` and `master`, the four missing states will be on the site.

**Comment by rogeruiz** [comment]
#70 and #82 are now merged in, so this issue can be closed.
